<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.11.1 on win32)" generated="20230127 10:23:05.646" rpa="false" schemaversion="3">
<suite id="s1" name="Demo2" source="C:\Users\40032395\OneDrive - LTTS\Robots_projets\AP_suite\demo2.robot">
<kw name="Create Session" library="RequestsLibrary" type="SETUP">
<arg>alias=petshop</arg>
<arg>url=https://petstore.swagger.io/v2</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<msg timestamp="20230127 10:23:05.796" level="INFO">Creating Session using : alias=petshop, url=https://petstore.swagger.io/v2, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" starttime="20230127 10:23:05.795" endtime="20230127 10:23:05.798"/>
</kw>
<test id="s1-t1" name="TC2" line="11">
<kw name="GET On Session" library="RequestsLibrary">
<var>${response}</var>
<arg>alias=petshop</arg>
<arg>url=pet/102</arg>
<doc>Sends a GET request on a previously created HTTP Session.</doc>
<msg timestamp="20230127 10:23:08.366" level="INFO">GET Request : url=https://petstore.swagger.io/v2/pet/102 
 path_url=/v2/pet/102 
 headers={'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} 
 body=None 
 </msg>
<msg timestamp="20230127 10:23:08.366" level="INFO">GET Response : url=https://petstore.swagger.io/v2/pet/102 
 status=404, reason=Not Found 
 headers={'Date': 'Fri, 27 Jan 2023 04:53:07 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, PUT', 'Access-Control-Allow-Headers': 'Content-Type, api_key, Authorization', 'Server': 'Jetty(9.2.9.v20150224)'} 
 body={"code":1,"type":"error","message":"Pet not found"} 
 </msg>
<msg timestamp="20230127 10:23:08.366" level="INFO">C:\Users\40032395\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'petstore.swagger.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(</msg>
<msg timestamp="20230127 10:23:08.367" level="FAIL">HTTPError: 404 Client Error: Not Found for url: https://petstore.swagger.io/v2/pet/102</msg>
<status status="FAIL" starttime="20230127 10:23:05.800" endtime="20230127 10:23:08.370"/>
</kw>
<kw name="Status Should Be" library="RequestsLibrary">
<arg>404</arg>
<doc>Fails if response status code is different than the expected.</doc>
<status status="NOT RUN" starttime="20230127 10:23:08.370" endtime="20230127 10:23:08.370"/>
</kw>
<kw name="Convert To String" library="BuiltIn">
<var>${response_Bbody}</var>
<arg>&amp;{response.json()}</arg>
<doc>Converts the given item to a Unicode string.</doc>
<status status="NOT RUN" starttime="20230127 10:23:08.370" endtime="20230127 10:23:08.371"/>
</kw>
<kw name="Should Contain" library="BuiltIn">
<arg>${response_Bbody}</arg>
<arg>pet not found</arg>
<doc>Fails if ``container`` does not contain ``item`` one or more times.</doc>
<status status="NOT RUN" starttime="20230127 10:23:08.371" endtime="20230127 10:23:08.371"/>
</kw>
<status status="FAIL" starttime="20230127 10:23:05.799" endtime="20230127 10:23:08.371">HTTPError: 404 Client Error: Not Found for url: https://petstore.swagger.io/v2/pet/102</status>
</test>
<status status="FAIL" starttime="20230127 10:23:05.650" endtime="20230127 10:23:08.372"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Demo2">Demo2</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
